apiVersion: v1
kind: Service
metadata:
  name: grafana-np-service
  labels:
    name: grafana-np-service
    app: sample-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
