apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-svc-demo
  name: myapp
spec:
  type: ClusterIP
  ports:
  - name: "db-service"
    port: 8091
    targetPort: 8091
  selector:
    app: my-api-demo
