apiVersion: v1
kind: Service
metadata:
  name: my-api-sevice
  labels:
    app: my-api-demo
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 8091
      nodePort: 31000
  selector:
    app: my-api-demo
