apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: my-api-demo
  endpoints:
  - interval: 30s
    path: /metrics
    port: http
