apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-app-hpa
  namespace: custom-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: autoscaling-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: autoscaling-service
      metricName: http_requests
      targetValue: 5
