apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-app-hpa
  namespace: custom-metrics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscaling-deploy
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Object
    object:
      target:
        type: Value
        value: 5
      metric:
        name: http_requests
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: main-route
