apiVersion: v1
kind: Service
metadata:
  name: autoscaling-service
  namespace: custom-metrics
  labels:
    release: prom
    app: autoscaling
spec:
  ports:
  - name: metrics-svc-port
    port: 80
    targetPort: 8080
  selector:
    app: autoscaling
